#!/bin/bash
#
# This script is executed whenever your appliance boots.  Here you can add
# commands to be executed before the system enters the first runlevel.  This
# could include loading kernel modules, starting daemons that aren't managed
# by init files, asking questions at the console, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance (oem =
# disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

if [ -f /etc/init.d/suse_studio_firstboot ]
then

  # Put commands to be run on the first boot of your appliance here
  echo "Running SUSE Studio first boot script..."

chkconfig --add rabbitmq-server
rcrabbitmq-server start
rcboss start
echo "Adding boss exchange/user and granting access"
rabbitmqctl add_vhost boss || true
rabbitmqctl add_user boss boss || true
rabbitmqctl set_permissions -p boss boss '.*' '.*' '.*' || true

skynet register robogrator
skynet enable robogrator

rcrabbitmq-server stop

rcmysql start
mysqladmin -u root password "opensuse"

cd /srv/www/obs/api/
RAILS_ENV="production"  rake db:setup
cd /srv/www/obs/webui/
RAILS_ENV="production" rake db:setup

rcmysql stop
chkconfig --add mysql

# Verify log directory ownership
chown -R wwwrun:www /srv/www/obs/webui/log/
chown -R wwwrun:www /srv/www/obs/api/log/

for i in memcached obsapidelayed apache2 obsrepserver obssrcserver \
         obsscheduler obsdispatcher obspublisher obswarden obssigner \
         obsworker boss boss-viewer
  do
    chkconfig --add $i
  done

sleep 10

fi